### ISSUE TITLE
badigeon.bundle/bundle should accept :aliases in some ways

### ISSUE THREAD

**Issue by zerg000000** [EwenG/badigeon#9]
I am facing an issue, I have no way to inlcude aliases' `:extra-paths` `:extra-deps` to bundle, so I cannot include `*.clj` and `*.jar` specified in aliases.

https://github.com/EwenG/badigeon/blob/eef05fcd3ad110b96b8ffee185143d4b676e3cd1/src/badigeon/bundle.clj#L175

minimum example
```clojure
; deps.edn
{:paths ["src"]
 :deps {badigeon/badigeon {...}}
 :aliases {:nice {:extra-deps {expound {...}}}}}

; badigeon call, no way to include deps in aliases "nice"
(require '[badigeon.bundle :as bundle]
         '[clojure.tools.deps.alpha.reader :as deps-reader])

(bundle/bundle "target/app"
               (let [deps-map (deps-reader/slurp-deps "deps.edn")
                 {:deps-map deps-map
                  :allow-unstable-deps? true
                  :libs-path "lib"}))
```

**Comment by EwenG** [comment]
The way I would do it:

```
(let [deps-map (deps-reader/slurp-deps "deps.edn")
      extra-deps (get-in deps-map [:aliases :nice :extra-deps])
      deps-map (update deps-map :deps merge extra-deps)]
    deps-map)
```
Same for extra-paths but with a `conj` instead of a `merge`

`:extra-deps` would be easy to support. But then users would expect things like` :extra-paths` to be supported as well. ` :extra-paths` is handled by tools.deps `make-classpath`. So this would require generating a classpath string and parsing it back.

I think aliases are useful when using tools.deps from the command line since there is no easy way to `merge` / `conj` from it.
But when using Clojure code, aliases can easily be replaced by data manipulation functions.

**Comment by zerg000000** [comment]
> ut when using Clojure co

Thanks for advance. That's currently what I am doing.
So this must be done manually, until tools.deps.alpha provide more function.

My current use case is using aliases to include aws lambda dependencies and sources path, so that I don't need to mix the lambda facade code into my app code.

**Comment by zerg000000** [comment]
I am okay with doing deps merge manually, should we close the issue or leave it as a reminder?

**Comment by EwenG** [comment]
I guess we can close it :)
